# Generated by Django 3.0.4 on 2020-03-24 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200324_1830'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='LABEL',
            new_name='label',
        ),
        migrations.AddField(
            model_name='item',
            name='price',
            field=models.FloatField(default='1', max_length=100),
            preserve_default=False,
        ),
    ]
