# Generated by Django 3.0.4 on 2020-03-24 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200324_2148'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='label',
            new_name='LABEL',
        ),
    ]
