# Generated by Django 3.0.4 on 2020-03-25 08:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200325_0856'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='LABEL',
            new_name='label',
        ),
    ]
