# Generated by Django 3.0.4 on 2020-04-13 17:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0022_auto_20200411_1020'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='cc_name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='cc_number',
        ),
    ]
