# Generated by Django 3.0.4 on 2020-04-14 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0023_auto_20200413_1744'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='category',
            field=models.CharField(choices=[('S', 'Shirt'), ('SW', 'Sport wear'), ('OW', 'Outwear'), ('S', 'Security'), ('L', 'Laptop')], max_length=2),
        ),
    ]
