# Generated by Django 3.0.4 on 2020-04-16 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0024_auto_20200414_1051'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='email',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='last_name',
        ),
    ]
