# Generated by Django 3.0.4 on 2020-04-17 11:51

from django.db import migrations
import django.utils.timezone
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0025_auto_20200416_1626'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billingaddress',
            name='location',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='payment_options',
        ),
        migrations.RemoveField(
            model_name='billingaddress',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='order',
            name='billing_address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='payment',
        ),
        migrations.AddField(
            model_name='billingaddress',
            name='countries',
            field=django_countries.fields.CountryField(default=django.utils.timezone.now, max_length=746, multiple=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
